#!/bin/busybox sh
set -eu

busybox mkdir /sysroot
busybox mount -t tmpfs sysroot /sysroot

busybox mkdir /sysroot/proc /sysroot/dev /sysroot/run /sysroot/tmp
busybox mount -t proc none /sysroot/proc
busybox mount -t devtmpfs none /sysroot/dev
busybox mount -t tmpfs none /sysroot/run
busybox mount -t tmpfs none /sysroot/tmp

busybox mkdir /sysroot/sbin /sysroot/usr /sysroot/usr/bin /sysroot/usr/sbin /sysroot/var /sysroot/var/log
busybox cp -a /bin /lib /sysroot
busybox chroot /sysroot /bin/busybox --install -s
busybox ln -s libc.so /sysroot/lib/libpthread.so.0
busybox ln -s libc.so /sysroot/lib/libc.so.6
busybox ln -s libc.so /sysroot/lib/ld-linux-x86-64.so.2
busybox ln -s lib /sysroot/lib64

busybox cp -a /etc /sysroot/etc

echo "Boot time: $(busybox cat /sysroot/proc/uptime)"

exec busybox switch_root /sysroot /sbin/init
