#!/bin/sh -efu
mkdir /vfat
mount /dev/vda1 /vfat

ip link set lo up
ip link set eth0 up
start-stop-daemon -S -p /run/udhcpc.eth0.pid -x /bin/sh -b -- -c "exec >/var/log/udhcpc.eth0.log 2>&1; exec udhcpc -i eth0 -s /etc/udhcpc/default.script -f"
